### ISSUE TITLE
Assistant Docs: Publishing Assistants and Featuring on sketch.com

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/developer.sketch.com#10]
Points to cover

- Publishing Assistant to npm 
- Steps required to ensure Assistant is featured on sketch.com
  - Add the `sketch assistant` keyword and set version to `1.0.0` or greater to indicate you want it listed on sketch.com
  - Fill in the `author` for attribution (personal or company)
  - Ensure special `sketch-assistants` metadata field has contents
  - Optionally add one of the following category keywords
    - `guidelines`
    - `organization`
    - `accessibility`
    - `ios`
    - `mac`
    - `windows`
    - `web`
    - `android`
- Recommendations around readmes
  - Do not repeat title/description at top
  - Document rules and options
  - Don't feature hardcore developer info on main readme, consider linking to a second md page

**Comment by christianklotz** [comment]
Looking good, only detail `organisation` › `organization` to match US English used elsewhere.

**Comment by paulozoom** [comment]
Only note: does it make sense to allow devs to opt-out of listing at any point with some boolean pref?

**Comment by jedrichards** [comment]
At the moment the idea is that if they didn't want it listed they should remove the `sketch-assistant` keyword ... 🤔

**Comment by paulozoom** [comment]
Do you think it’s possible, or likely, that they’ll want to come up in search but somehow not be officially listed?

Another note: I’ve noticed that here you’ve mentioned:
> Ensure special `sketch-assistants` metadata field has contents

However, at least Tidy has this field in the singular, `sketch-assistant`. Similarly, some of our assistants seem to have the key in singular, others in plural. Should I build tolerance for this and allow both?

**Comment by jedrichards** [comment]
@paulozoom 

Let's use this issue as the definitive spec for how we want it to work, and if our Assistants diverge, then it's a bug on our end to fix.

I see your point with the search results thing. Maybe we could use a combination of two keywords for sketch.com listing?

```
{
  "keywords": [
    "sketch assistant",
    "public"
  ],
  "sketch-assistant": { ... }
}
```

Then you can query for both keywords:

```
curl -XGET "http://registry.npmjs.com/-/v1/search?text=keywords:sketch%20assistant+public"
```

Maybe it'll help if we generate a definitive list of how to find Assistants and filter them:

1. Search for keywords `sketch%20assistant+public` for initial list
1. Package MUST have a `sketch-assistant` field, which is an object with `title` and `description` strings
1. Package MUST have a version >= `1.0.0`

**Comment by jedrichards** [comment]
And sorry, I was incorrectly hyphenating the keyword above, should be `sketch assistants`, with a space.

**Comment by paulozoom** [comment]
@jedrichards But singular, not plural right? In any case if I search for singular NPM seems to return both, but the guidance for developers is that everything in metadata is `assistant`, not `assistants`, right?

With regards to the "public" keyword, I have some reservations about making that opt-in rather than opt-out, but I have the similar amount of reservations about making it opt-out. 

Two things are easier to forget than one thing, and I hope it doesn't impact the number of assistants we have. It’s easy for us to just block something we don't want to see in the blocklist, but harder to force something to show if we're not even aware of it. Does that make sense?

I’m not opposed to it, but I’d like to know if you have thoughts over the opt-in/-out question, and what led you to decide for opt-in.

**Comment by jedrichards** [comment]
Yes singular, `sketch assistant`. Fixed typo above 🤪

Some of our packages have the `sketch assistants` (pluralised) keyword, e.g. [here](https://github.com/sketch-hq/sketch-assistants/blob/main/packages/cli/package.json#L12). This is because such a package isn't an actual Sketch Assistant, but rather is related to Sketch Assistants as a topic, so it seemed like a descriptive keyword. In any case, such packages wouldn't meet the rest of our criteria.

In a sense, the whole thing is opt-in by definition - people are free to make all sorts of mistakes and omissions in their package.json. As long as we carefully document our requirements then I hope that's enough. The idea with using two keywords is just so people can toggle on and off the `public` keyword, while keeping the generally descriptive/useful `sketch assistant` keyword.

The approach is based on [Gatsby's way of taking plugin submissions](https://www.gatsbyjs.org/contributing/submit-to-plugin-library/) - they require two keywords too `gatsby` and `gatsby-plugin` 🤷‍♂️ 

Most people will begin creating an Assistant by cloning our https://github.com/sketch-hq/sketch-assistant-template template repo.

So we could add the `sketch assistant` and `public` keywords there, so new Assistants will by default be listed on sketch.com. In that sense we have some control over whether its opt-in or opt-out ...

**Comment by paulozoom** [comment]
> So we could add the `sketch assistant` and `public` keywords there, so new Assistants will by default be listed on sketch.com. In that sense we have some control over whether its opt-in or opt-out ...

I think that makes sense, to make the template totally ready for publishing. You could perhaps add the `sketch-assistant` bit with all of its fields (if you leave it as a blank string, the import script will filter it out). The blank bits will probably prompt people to fill them out. And the “Publish the Assistant” section of the README could clarify what the `public` is for — I think that might be a little cryptic, but I'm not wholly familiar with npm patterns.

**Comment by jedrichards** [comment]
Leveraging keywords for this sort of thing is not something I've seen anywhere else, aside from in Gatsby's docs. So it'll be a fairly unfamiliar/cryptic experience for most, so our documentation will be key.
