### ISSUE TITLE
Assistant Docs: One Click Install Link

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/developer.sketch.com#19]
- Document the link format
- Describe how to craft a link that installs an Assistant published to npm as a url Assistant

**Comment by christianklotz** [comment]
Given that this is part of the app URL scheme it may be best to either:

- Add it as a redirecting page to the Assistants section and add a paragraph to https://developer.sketch.com/app
- Add the link documentation to https://developer.sketch.com/app and cover the npm aspect within a page in Assistants doc
