### ISSUE TITLE
Creating multi style text layer through the Sketch Api

### ISSUE THREAD

**Issue by petrvanblokland** [sketch-hq/developer.sketch.com#44]
Maybe I am missing how it is done, but what is the way to create multi style text layers, using the method available in the Sketch 68 Api?

**Comment by christianklotz** [comment]
It's best to use https://sketchplugins.com for plugin development questions. You may also be interested to look into the [style](https://developer.sketch.com/reference/api/#style) and [`NSAttributedString`](https://developer.apple.com/documentation/foundation/nsattributedstring) documentation.

Use issues in this repository to report anything regarding content, typos, etc. on the developer.sketch.com website. Thank you!
